#!/bin/sh

# Make the mouse visible
xsetroot -cursor_name left_ptr

# Avoid doubling ruls
bspc rule -r "*"

# Workspace setup
bspc monitor -d I II III

## Wallpaper setting
pkill xwinwrap | pkill hsetroot | pkill sxiv

# Image
hsetroot -cover ~/Images/Walls/1.jpg
#hsetroot -solid "#000000"

# Animated background
#xwinwrap -ov -ni -fs -- mpv -vo x11 -wid WID --keepaspect=no --pause=no --loop ~/Images/Walls/1.gif &
#xwinwrap -ov -ni -fs -- sxiv -a -e WID -f -b -g 1366x768  ~/Images/Walls/1.gif &

# Compositor
pkill picom
picom -b &

# Default prefered settings
amixer -q set Master 100% &
xbacklight -set 60 &

# Workspaces settings
bspc rule -a 'Firefox' desktop='^1'
bspc rule -a 'mpv' desktop='^3' center=on state=pseudo_tiled
bspc rule -a 'nnn' center=on state=pseudo_tiled

# Split ratio and gapless monocle
bspc config split_ratio             0.52
bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

# Lemonbar
pkill lemonbar | pkill panel.sh
~/panel.sh | lemonbar -g x20 -f "-xos4-terminus-medium-r-normal--12-120-72-72-c-60-iso10646-1" -o -1 -f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" -B "#002b36" -F "#657b83" &

## Nord theme
# Border gaps settings
BW=2
bspc config border_width $BW
bspc config window_gap -2
bspc config top_padding 22
for side in right bottom left ; do
    bspc config ${side}_padding $BW
done

# Colors settings
bspc config focused_border_color    "#6c71c4"
bspc config normal_border_color     "#073642"
bspc config active_border_color     "#073642"
bspc config urgent_border_color     "#d33682"

# Polybar
#pkill polybar
#polybar example & disown
